Webscraping with pandas

In [1]:
import pandas as pd

In [3]:
url = "https://www.basketball-reference.com/leagues/NBA_2024_standings.html"
tables = pd.read_html(url)

In [6]:
# Podgląd nazw tabel
for i, t in enumerate(tables):
    print(f"--- TABLE {i} ---")
    print(t.head(), "\n")

--- TABLE 0 ---
     Eastern Conference   W   L   W/L%    GB   PS/G   PA/G    SRS
0       Boston Celtics*  64  18  0.780     —  120.6  109.2  10.75
1      New York Knicks*  50  32  0.610  14.0  112.8  108.2   4.36
2      Milwaukee Bucks*  49  33  0.598  15.0  119.0  116.4   2.44
3  Cleveland Cavaliers*  48  34  0.585  16.0  112.6  110.2   1.98
4        Orlando Magic*  47  35  0.573  17.0  110.5  108.4   1.48

--- TABLE 1 ---
        Western Conference   W   L   W/L%   GB   PS/G   PA/G   SRS
0   Oklahoma City Thunder*  57  25  0.695    —  120.1  112.7  7.36
1          Denver Nuggets*  57  25  0.695    —  114.9  109.6  5.23
2  Minnesota Timberwolves*  56  26  0.683  1.0  113.0  106.5  6.39
3    Los Angeles Clippers*  51  31  0.622  6.0  115.6  112.3  3.41
4        Dallas Mavericks*  50  32  0.610  7.0  117.9  115.6  2.30

--- TABLE 2 ---
    Eastern Conference                  W                  L  \
0    Atlantic Division  Atlantic Division  Atlantic Division
1      Boston Celtics*                 64                 18
2     New York Knicks*                 50                 32
3  Philadelphia 76ers*                 47                 35
4        Brooklyn Nets                 32                 50

                W/L%                 GB               PS/G               PA/G  \
0  Atlantic Division  Atlantic Division  Atlantic Division  Atlantic Division
1               .780                  —              120.6              109.2
2               .610               14.0              112.8              108.2
3               .573               17.0              114.6              111.5
4               .390               32.0              110.4              113.3

                 SRS
0  Atlantic Division
1              10.75
2               4.36
3               2.51
4              -3.02

--- TABLE 3 ---
        Western Conference                   W                   L  \
0       Northwest Division  Northwest Division  Northwest Division
1   Oklahoma City Thunder*                  57                  25
2          Denver Nuggets*                  57                  25
3  Minnesota Timberwolves*                  56                  26
4                Utah Jazz                  31                  51

                 W/L%                  GB                PS/G  \
0  Northwest Division  Northwest Division  Northwest Division
1                .695                   —               120.1
2                .695                   —               114.9
3                .683                 1.0               113.0
4                .378                26.0               115.7

                 PA/G                 SRS
0  Northwest Division  Northwest Division
1               112.7                7.36
2               109.6                5.23
3               106.5                6.39
4               120.5               -4.22

In [4]:
east_standings = tables[0]  # Eastern Conference
west_standings = tables[1]  # Western Conference

In [5]:
east_standings.head()

     Eastern Conference   W   L   W/L%    GB   PS/G   PA/G    SRS
0       Boston Celtics*  64  18  0.780     —  120.6  109.2  10.75
1      New York Knicks*  50  32  0.610  14.0  112.8  108.2   4.36
2      Milwaukee Bucks*  49  33  0.598  15.0  119.0  116.4   2.44
3  Cleveland Cavaliers*  48  34  0.585  16.0  112.6  110.2   1.98
4        Orlando Magic*  47  35  0.573  17.0  110.5  108.4   1.48

Webscraping with BeautifulSoup

In [13]:
import requests
from bs4 import BeautifulSoup, Comment
import pandas as pd

url = "https://www.basketball-reference.com/leagues/NBA_2024_standings.html"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

# Szukamy ukrytych tabel w komentarzach
comments = soup.find_all(string=lambda text: isinstance(text, Comment))

# Przeszukujemy komentarze pod kątem tabel HTML
for c in comments:
    if 'table' in c:
        comment_soup = BeautifulSoup(c, "html.parser")
        tables = comment_soup.find_all("table")
        for t in tables:
            print(t.get("id"))  # pokaże ID każdej tabeli

expanded_standings
team_vs_team

In [15]:
# Wyciągnięcie pełnej tabeli expanded_standings
for c in comments:
    if 'expanded_standings' in c:
        comment_soup = BeautifulSoup(c, "html.parser")
        table = comment_soup.find("table", {"id": "expanded_standings"})
        df_expanded = pd.read_html(str(table))[0]
        break  # nie musimy sprawdzać dalej

df_expanded.head()

/tmp/ipykernel_15852/2102395496.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_expanded = pd.read_html(str(table))[0]

  Unnamed: 0_level_0      Unnamed: 1_level_0 Unnamed: 2_level_0  Place         \
                  Rk                    Team            Overall   Home   Road
0                  1          Boston Celtics              64-18   37-4  27-14
1                  2          Denver Nuggets              57-25   33-8  24-17
2                  3   Oklahoma City Thunder              57-25   33-8  24-17
3                  4  Minnesota Timberwolves              56-26  30-11  26-15
4                  5    Los Angeles Clippers              51-31  25-16  26-15

  Conference        Division              ... All-Star Margin        Month  \
           E      W        A     C    SE  ...     Post     ≤3    ≥10   Oct
0      41-11   23-7     15-2  13-5  13-4  ...     21-6    6-7   42-5   3-0
1       24-6  33-19      8-2   8-2   8-2  ...     21-6    6-6  28-10   4-0
2       21-9  36-16      6-4   6-4   9-1  ...     20-8    6-3  32-10   3-1
3      19-11  37-15      6-4   6-4   7-3  ...    17-10    7-6  32-10   1-2
4       21-9  30-22      6-4   6-4   9-1  ...    15-14    6-4  28-17   3-1


    Nov   Dec   Jan  Feb   Mar  Apr
0  11-4  12-2  11-5  9-1  12-4  6-2
1   9-6  10-5  10-5  8-3  11-4  5-2
2   9-5  10-3  11-6  8-3  11-4  5-3
3  13-2  10-3  10-7  8-3   9-6  5-3
4   5-9  11-2  12-3  6-5  10-7  4-4

[5 rows x 24 columns]